name: image deploy S3

on:
  push:
   branches:
      - "master"
  
  
jobs:
  
  deploy-S3 bucket:
    name: Client
    runs-on: ubuntu-latest
    uses: actions/checkout@v3


    steps:
      - name: check out the repo
        uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1
